;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-slash
        dabbrev-expand
        forward-sexp
        kill-region
        mc/vertical-align-with-space
        org-ctrl-c-ctrl-c
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
