(let* ((gc-cons-threshold most-positive-fixnum)) ;; gc trick
  (load-file "elisp/010--early-functions.el")
  (load-file "elisp/011--early-shortcuts.el")
  (load-file "elisp/012--early-packages-and-server.el")
  (load-file "elisp/013--early-vars.el")
  (load-file "elisp/014--early-dired.el")
  (load-file "elisp/015--early-shell.el")
  (load-file "elisp/020--paths.el")
  (load-file "elisp/030--nav-nav.el")
  (load-file "elisp/040--helm-hydra.el")
  (load-file "elisp/050--ui.el")
  (load-file "elisp/060--interactive.el")
  (load-file "elisp/070--dev.el")
  (load-file "elisp/071--elisp.el")
  (load-file "elisp/072--python.el")
  (load-file "elisp/080--modules.el")
  (load-file "elisp/081--modules--llm.el")
  (load-file "elisp/090--functions.el")
  (load-file "elisp/100--org.el")
  (load-file "elisp/101--org-latex.el")
  (when priv-conf-file (load-file priv-conf-file)))
(message "Emacs started in %s" (emacs-init-time))
