(defun load-el (rel-path) (load-file (expand-file-name rel-path user-emacs-directory)))
(let* ((gc-cons-threshold most-positive-fixnum)) ;; gc trick
  (load-el "elisp/010--early-functions.el")
  (load-el "elisp/011--early-shortcuts.el")
  (load-el "elisp/012--early-packages-and-server.el")
  (load-el "elisp/013--early-vars.el")
  (load-el "elisp/014--early-dired.el")
  (load-el "elisp/015--early-shell.el")
  (load-el "elisp/020--paths.el")
  (load-el "elisp/030--nav-nav.el")
  (load-el "elisp/040--helm-hydra.el")
  (load-el "elisp/050--ui.el")
  (load-el "elisp/060--interactive.el")
  (load-el "elisp/070--dev.el")
  (load-el "elisp/071--elisp.el")
  (load-el "elisp/072--python.el")
  (load-el "elisp/080--modules.el")
  (load-el "elisp/090--functions.el")
  (load-el "elisp/100--org.el")
  (load-el "elisp/102--org-cur.el")
  (load-el "elisp/101--org-latex.el")
  (load-el "elisp/081--modules--llm.el")
  (when priv-conf-file (load-file priv-conf-file)))
(message "Emacs started in %s" (emacs-init-time))
